### ISSUE TITLE
Error when loading edb 

### ISSUE THREAD

**Issue by aladshaw3** [nawi-hub/proteuslib#150]
The <code>edb load --bootstrap -d edb</code> tool is throwing errors. Looks like it is associated with the <code>component.json</code> and maybe the <code>reaction.json</code> data files located in <code>proteuslib/edb/data</code>. Error message below. 

(proteuslib-dev) 1pi@opal:~/projects/proteuslib$ edb load --bootstrap -d edb
Loaded 2 record(s) into collection 'base'
Traceback (most recent call last):
  File "/home/1pi/miniconda3/envs/proteuslib-dev/bin/edb", line 33, in <module>
    sys.exit(load_entry_point('proteuslib', 'console_scripts', 'edb')())
  File "/home/1pi/miniconda3/envs/proteuslib-dev/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/1pi/miniconda3/envs/proteuslib-dev/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/1pi/miniconda3/envs/proteuslib-dev/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/1pi/miniconda3/envs/proteuslib-dev/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/1pi/miniconda3/envs/proteuslib-dev/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/1pi/projects/proteuslib/proteuslib/edb/commands.py", line 124, in load_data
    _load_bootstrap(url, database)
  File "/home/1pi/projects/proteuslib/proteuslib/edb/commands.py", line 199, in _load_bootstrap
    _load(path.open("r"), t, url, database, False)
  File "/home/1pi/projects/proteuslib/proteuslib/edb/commands.py", line 143, in _load
    input_data = json.load(input_file)
  File "/home/1pi/miniconda3/envs/proteuslib-dev/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/home/1pi/miniconda3/envs/proteuslib-dev/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/1pi/miniconda3/envs/proteuslib-dev/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/1pi/miniconda3/envs/proteuslib-dev/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

**Comment by lbianchi-lbl** [comment]
I think a typo (Freudian slip?) might (part of) the cause for this? https://github.com/nawi-hub/proteuslib/blob/0dc9b30cd6b0881b9d28b63919e76154e16fb6f7/proteuslib/edb/data/component.json#L1

**Comment by aladshaw3** [comment]
> 
> 
> I think a typo (Freudian slip?) might (part of) the cause for this?
> 
> https://github.com/nawi-hub/proteuslib/blob/0dc9b30cd6b0881b9d28b63919e76154e16fb6f7/proteuslib/edb/data/component.json#L1

That is part of the issue, but there is something else wrong. Probably an issue with an open or closed curly brace where their shouldn't be.

**Comment by lbianchi-lbl** [comment]
> > I think a typo (Freudian slip?) might (part of) the cause for this?
> > https://github.com/nawi-hub/proteuslib/blob/0dc9b30cd6b0881b9d28b63919e76154e16fb6f7/proteuslib/edb/data/component.json#L1
> 
> That is part of the issue, but there is something else wrong. Probably an issue with an open or closed curly brace where their shouldn't be.

I think you're right, i.e. I can confirm that removing that string alone (with or without the `{` and `:`, too) is not enough to produce a valid JSON file. I can imagine this is probably going to be easier to fix for someone who's familiar with how the data is supposed to look like in that file.
