### ISSUE TITLE
Property Interrogator Tool Compatibility

### ISSUE THREAD

**Issue by adam-a-a** [nawi-hub/proteuslib#153]
The [IDAES Property Interrogator Tool](https://idaes-pse.readthedocs.io/en/stable/technical_specs/model_libraries/generic/property_models/interrogator.html) would be useful for determining required properties in Proteuslib unit models:

> The IDAES Property Interrogator tool allows a user to define a general flowsheet structure and interrogate it for the full list of properties that will be required, thus informing them of what methods they will need to define in their property package(s).

However, I was unable to successfully apply this tool while probing the RO model. I am not yet certain if this is because of a mistake I made when trying to apply methods from the Interrogator Tool, or if either (i) our Proteuslib unit models or (ii) the tool itself need to be modified for successfully probing unit models.

- [ ] Determine whether a compatibility issue exists between the Property Interrogator Tool and the RO model
- [ ] If so, make appropriate adjustments to enable compatibility

**Comment by andrewlee94** [comment]
@adam-a-a What happened when you tried to use the interrogator tool?

**Comment by adam-a-a** [comment]
@andrewlee94 First, I get the following error when trying it out on the ReverseOsmosis0D model (which is due to the fact that we raise a configuration error if any phase other than liquid is specified): 

```
Traceback (most recent call last):
  File "C:\Users\adama\Anaconda3\envs\proteuslib2\lib\site-packages\idaes\core\process_block.py", line 37, in _rule_default
    b.build()
  File "C:\Users\adama\my-nawi-hub\proteuslib\proteuslib\unit_models\reverse_osmosis_0D.py", line 283, in build
    self._process_config()
  File "C:\Users\adama\my-nawi-hub\proteuslib\proteuslib\unit_models\reverse_osmosis_0D.py", line 221, in _process_config
    .format([p for p in self.config.property_package.phase_list]))
idaes.core.util.exceptions.ConfigurationError: RO model only supports one liquid phase ['Liq'],the property package has specified the following phases ['Liq', 'Vap']
ERROR: Constructing component 'fs.unit' from data=None failed:
    ConfigurationError: RO model only supports one liquid phase ['Liq'],the
    property package has specified the following phases ['Liq', 'Vap']
Traceback (most recent call last):
  File "C:\Users\adama\Anaconda3\envs\proteuslib2\lib\site-packages\IPython\core\interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-b92ac4e9d123>", line 1, in <module>
    runfile('C:/Users/adama/my-nawi-hub/proteuslib/my-sandbox/sim_1dro.py', wdir='C:/Users/adama/my-nawi-hub/proteuslib/my-sandbox')
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.3.4\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.3.4\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/adama/my-nawi-hub/proteuslib/my-sandbox/sim_1dro.py", line 54, in <module>
    "property_package": m.fs.properties})
  File "C:\Users\adama\Anaconda3\envs\proteuslib2\lib\site-packages\pyomo\core\base\block.py", line 544, in __setattr__
    self.add_component(name, val)
  File "C:\Users\adama\Anaconda3\envs\proteuslib2\lib\site-packages\pyomo\core\base\block.py", line 1089, in add_component
    val.construct(data)
  File "C:\Users\adama\Anaconda3\envs\proteuslib2\lib\site-packages\pyomo\core\base\block.py", line 1986, in construct
    self._getitem_when_not_present(_idx)
  File "C:\Users\adama\Anaconda3\envs\proteuslib2\lib\site-packages\pyomo\core\base\block.py", line 1911, in _getitem_when_not_present
    obj = self._rule(_block, idx)
  File "C:\Users\adama\Anaconda3\envs\proteuslib2\lib\site-packages\pyomo\core\base\util.py", line 304, in __call__
    return self._fcn(parent, idx)
  File "C:\Users\adama\Anaconda3\envs\proteuslib2\lib\site-packages\idaes\core\process_block.py", line 37, in _rule_default
    b.build()
  File "C:\Users\adama\my-nawi-hub\proteuslib\proteuslib\unit_models\reverse_osmosis_0D.py", line 283, in build
    self._process_config()
  File "C:\Users\adama\my-nawi-hub\proteuslib\proteuslib\unit_models\reverse_osmosis_0D.py", line 221, in _process_config
    .format([p for p in self.config.property_package.phase_list]))
idaes.core.util.exceptions.ConfigurationError: RO model only supports one liquid phase ['Liq'],the property package has specified the following phases ['Liq', 'Vap']
```

**Comment by adam-a-a** [comment]
The error above can be circumvented by a conditional that disables the RaiseConfigurationError if the PropertyInterrogatorBlock is detected. So, when I temporarily comment out the function that checks for config errors, I get the following: 
```
Traceback (most recent call last):
  File "C:\Users\adama\Anaconda3\envs\proteuslib2\lib\site-packages\idaes\core\process_block.py", line 37, in _rule_default
    b.build()
  File "C:\Users\adama\my-nawi-hub\proteuslib\proteuslib\unit_models\reverse_osmosis_0D.py", line 293, in build
    units=units_meta('length')*units_meta('pressure')**-1*units_meta('time')**-1,
TypeError: unsupported operand type(s) for ** or pow(): 'NoneType' and 'int'
ERROR: Constructing component 'fs.unit' from data=None failed: TypeError:
    unsupported operand type(s) for ** or pow(): 'NoneType' and 'int'
Traceback (most recent call last):
  File "C:\Users\adama\Anaconda3\envs\proteuslib2\lib\site-packages\IPython\core\interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-b92ac4e9d123>", line 1, in <module>
    runfile('C:/Users/adama/my-nawi-hub/proteuslib/my-sandbox/sim_1dro.py', wdir='C:/Users/adama/my-nawi-hub/proteuslib/my-sandbox')
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.3.4\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.3.4\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/adama/my-nawi-hub/proteuslib/my-sandbox/sim_1dro.py", line 54, in <module>
    "property_package": m.fs.properties})
  File "C:\Users\adama\Anaconda3\envs\proteuslib2\lib\site-packages\pyomo\core\base\block.py", line 544, in __setattr__
    self.add_component(name, val)
  File "C:\Users\adama\Anaconda3\envs\proteuslib2\lib\site-packages\pyomo\core\base\block.py", line 1089, in add_component
    val.construct(data)
  File "C:\Users\adama\Anaconda3\envs\proteuslib2\lib\site-packages\pyomo\core\base\block.py", line 1986, in construct
    self._getitem_when_not_present(_idx)
  File "C:\Users\adama\Anaconda3\envs\proteuslib2\lib\site-packages\pyomo\core\base\block.py", line 1911, in _getitem_when_not_present
    obj = self._rule(_block, idx)
  File "C:\Users\adama\Anaconda3\envs\proteuslib2\lib\site-packages\pyomo\core\base\util.py", line 304, in __call__
    return self._fcn(parent, idx)
  File "C:\Users\adama\Anaconda3\envs\proteuslib2\lib\site-packages\idaes\core\process_block.py", line 37, in _rule_default
    b.build()
  File "C:\Users\adama\my-nawi-hub\proteuslib\proteuslib\unit_models\reverse_osmosis_0D.py", line 293, in build
    units=units_meta('length')*units_meta('pressure')**-1*units_meta('time')**-1,
TypeError: unsupported operand type(s) for ** or pow(): 'NoneType' and 'int'
```

**Comment by adam-a-a** [comment]
It seems that since we define units throughout the RO model based on the units of the imported property package, this causes an error because no units are derived from the following (hence the `Nonetype` found in traceback): 

` units_meta = self.config.property_package.get_metadata().get_derived_units
`

I don't fully understand the workflow behind getting metadata/deriving units yet. I'd have to look into this further and dive into the code behind the Interrogator Tool, but I am guessing that you might know what the problem is @andrewlee94.

**Comment by andrewlee94** [comment]
OK, so:

1. Property Interrogator needs to handle units which support limited phases. This is a tricky one however, as there is a chicken and egg problem. Ideally we would get the unit model to tell us it supports only one phase and build the property package accordingly, but the property package comes first. We could get the user to state that only liquid phase is required, but that sort of defeats the purpose of the tool.
2. Property Interrogator needs to define a set of base units. This is easily done, and should probably just use SI so that unit consistency is maintained (we could also do dimensionless for everything, but who knows what problems that might cause).

**Comment by andrewlee94** [comment]
Looking a bit further a the issue with the number of phases I am not sure there is much we can do besides manually telling the interrogator what phases are needed. In this case, the RO model is specifying that it only supports a single phase with a specific name - i.e. the unit model is applying specific limitations to the system. We probably _could_ define a way for unit models to define this (as a class method) and then have a way for the interrogator to look up all the imported unit models and identify what phases (and components) are required, but that sounds like a lot of work.

So, the easier, but more user-intensive, approach is to add a way for users to manually define phases and components when setting up the interrogator, and leaving it up to the user to make sure this is consistent with any unit model limitations.

**Comment by andrewlee94** [comment]
@adam-a-a Could you try out https://github.com/IDAES/idaes-pse/pull/415. This hopefully fixes those two issues.
